const express = require("express");
const bcrypt = require("bcrypt");
const router = express.Router();
const UserSc = require("../Schema/userSchema");
const jwt = require("jsonwebtoken");
/**
 * @swagger
 * components:
 *  schemas:
 *      User:
 *          type: object
 *          properties:
 *              id:
 *                  type: string
 *                  description: id of the user generated by MongoDB
 *              name:
 *                  type: string
 *                  description: name of the user
 *              email:
 *                  type: string
 *                  description: email of the user
 *              password:
 *                  type: string
 *                  description: password of the user
 * 
*/

/**
 * @swagger
 * /user/register:
 *  post:
 *      summary: Register a new user
 *      tags: [Users]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/User'
 *      responses:
 *        200:
 *          description: User added successfully
 *          content:
 *            application/json:
 *              schema:
 *                $ref: '#/components/schemas/User'
 */




router.post("/register", (req, res) => {
  const { name, email, password } = req.body;
  try {
    bcrypt.hash(password, 5, async (err, hash) => {
      if (err) {
        res.send("somehting went wrong hashing" + err);
      } else {
        const user = new UserSc({
          name,
          email,
          password: hash,
        });
        await user.save();
        res.send("user have added");
      }
    });
  } catch (error) {
    res.send(error);
  }
});

/**
 * @swagger
 * components:
 *  schemas:
 *      Login:
 *          type: object
 *          properties:
 *              email:
 *                  type: string
 *                  description: Email of the user
 *              password:
 *                  type: string
 *                  description: Password of the user
 * 
*/

/**
 * @swagger
 * /user/login:
 *  post:
 *      summary: User login
 *      tags: [Users]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/Login'
 *      responses:
 *        200:
 *          description: User logged in successfully
 *          content:
 *            application/json:
 *              schema:
 *                $ref: '#/components/schemas/Login'
 *        401:
 *          description: Invalid credentials
 */

router.post("/login", async (req, res) => {
  const { email, password } = req.body;
  try {
    const user = await UserSc.findOne({ email });
    if (user) {
      bcrypt.compare(password, user.password, (err, result) => {
        if (result) {
          const token = jwt.sign(
            { userID: user._id, name: user.name },
            "masai",
            {
              expiresIn: "1h",
            }
          );
          res.cookie("token", token, { maxAge: 7*24*60*60*1000, httpOnly: true, sameSite: "none", secure: true });
          res.send({ msg: "login successfully", token: token });
        } else {
          res.status(401).send("wrong password");
        }
      });
    } else {
      res.status(400).send("user not found");
    }
  } catch (error) {
    res.send(error);
  }
});

/**
 * @swagger
 * components:
 *  schemas:
 *      LogoutResponse:
 *          type: object
 *          properties:
 *              message:
 *                  type: string
 *                  description: Message indicating the logout status
 * 
*/

/**
 * @swagger
 * /logout:
 *  get:
 *      summary: Logout user
 *      tags: [Users]
 *      responses:
 *        200:
 *          description: Logout successful
 *          content:
 *            application/json:
 *              schema:
 *                $ref: '#/components/schemas/LogoutResponse'
 */


router.get("/logout" , (req, res) => {
  
   res.clearCookie("token");
   res.clearCookie("refreshToken");

  res.send("logout successfully")
})

module.exports = router;
